### ISSUE TITLE
Update to Mongoid 2.0.0.beta.20

### ISSUE THREAD

**Issue by ticktricktrack** [kristianmandrup/roles_mongoid#4]
When I try to update mongoid to beta.20

I get this error

```
Bundler could not find compatible versions for gem "rails3_artifactor":
    In Gemfile:
      cream depends on
        rails3_artifactor (~> 0.2.4)

      rails3_artifactor (0.3.1)
```

Why do I want to do this in the first place? Well to match bson, bson_ext and mongo versions at 1.1.4

I guess I can close this myself. But first I want to dig a bit deeper into Cream.

**Comment by kristianmandrup** [comment]
Oh, I guess the Cream Gemfile needs to be updated to match the Rakefile. Should be rails3_artifactor 0.3.1 everywhere. Not sure how to best resolve the bson issue. Any ideas? I would think this should be handled by mongoid itself?

**Comment by ticktricktrack** [comment]
I think you can close this, Bundler wasn't loading the proper cream version due to an older version of devise specified by me. 

Lesson learned: Check my Gemfile.lock more often.

**Comment by kristianmandrup** [comment]
OK, good luck on your further adventures ;)
