### ISSUE TITLE
Generator Issues

### ISSUE THREAD

**Issue by mleung** [kristianmandrup/roles_mongoid#5]
Whenever I try to run a generator (rails g mongoid:roles User --strategy admin_flag) I get this error:

.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require': no such file to load -- migration_assist (LoadError)

Has anyone else seen this? Thanks!

**Comment by kristianmandrup** [comment]
migration_assist is a gem I made to help with migrations for Active Record. Mongoid roles should not have a dependency on this gem. I will look into it ASAP. Thanks.

**Comment by mleung** [comment]
Cool! Thanks so much.

**Comment by kristianmandrup** [comment]
Oh, I discovered that rails_artifactor still contains a few require 'migration_assist' statements. This is a "bug".
In the _file_name_ folder of that project, the statement in _artifacts.rb_ file should be deleted and the _migration.rb_ file should be moved to the _migration_assist_ project. A much better design I think.

For now just install migration_assist or add it in your Gemfile, then I will try to fix this ASAP. or try fix this yourself and send me a few pull requests. Thanks.

**Comment by mleung** [comment]
I threw migration_assist in my gemfile for now. No more error. Thanks!
